module Data.HList where

open import Data.Fin using (Fin; zero; suc)
open import Data.List using (List; []; _∷_; lookup)

----------------------------------------------------------------------------------------------------
-- Heterogenous lists
----------------------------------------------------------------------------------------------------

-- The conjunction of a list of types
-- generated by applying an indexing function to a list of type indices.
data HList {ℓ ℓ'} {α : Set ℓ} (f : α → Set ℓ') : List α → Set ℓ' where
  []  :            HList f []
  _∷_ : ∀ {x xs} → f x → HList f xs → HList f (x ∷ xs)

-- Transport the indexing function along a transformation quantified over all type indices.
hmap : ∀ {ℓ ℓ' ℓ''} → {α : Set ℓ} {f : α → Set ℓ'} {g : α → Set ℓ''} →
       (∀ {x} → f x → g x) → ∀ {xs} → HList f xs → HList g xs
hmap h []       = []
hmap h (y ∷ ys) = h y ∷ hmap h ys

-- Cast a heterogenous list whose indexing function is constant into a homogenous list.
forget : ∀ {ℓ ℓ'} → {α : Set ℓ} {β : Set ℓ'} {xs : List α} → HList (λ _ → β) xs → List β
forget []       = []
forget (y ∷ ys) = y ∷ forget ys

-- Retrieve the element of the list at the given index.
hlookup : ∀ {ℓ ℓ'} → {α : Set ℓ} {f : α → Set ℓ'} {xs : List α} → HList f xs → ∀ i → f (lookup xs i)
hlookup (y ∷ ys) zero    = y
hlookup (y ∷ ys) (suc i) = hlookup ys i

-- The derived form mapping a heterogenous list into a homogenous list.
forget-map : ∀ {ℓ ℓ' ℓ''} → {α : Set ℓ} {β : Set ℓ'} {f : α → Set ℓ''} →
             (∀ {x} → f x → β) → ∀ {xs} → HList f xs → List β
forget-map h ys = forget (hmap h ys)
