module Data.HSum where

open import Data.Fin using (Fin; zero; suc)
open import Data.HList using (HList; _∷_)
open import Data.List using (List; _∷_; lookup)

----------------------------------------------------------------------------------------------------
-- Heterogenous sum types
----------------------------------------------------------------------------------------------------

-- The disjunction of a list of types
-- generated by applying an indexing function to a list of type indices.
data HSum {ℓ ℓ'} {α : Set ℓ} (f : α → Set ℓ') : List α → Set ℓ' where
  here : ∀ {x xs} → f x → HSum f (x ∷ xs)
  next : ∀ {x xs} → HSum f xs → HSum f (x ∷ xs)

-- Transport the indexing function along a transformation quantified over all type indices.
smap : ∀ {ℓ ℓ' ℓ''} → {α : Set ℓ} {f : α → Set ℓ'} {g : α → Set ℓ''} →
       (∀ {x} → f x → g x) → ∀ {xs} → HSum f xs → HSum g xs
smap h (here y)  = here (h y)
smap h (next ys) = next (smap h ys)

-- Transport the indexing function along a transformation quantified over all type indices,
-- which has access to corresponding elements of a heterogenous list. 
smap-with : ∀ {ℓ ℓ' ℓ'' ℓ'''} → {α : Set ℓ} {f : α → Set ℓ'} {g : α → Set ℓ''} {r : α → Set ℓ'''} →
            (∀ {x} → r x → f x → g x) → ∀ {xs} → HList r xs → HSum f xs → HSum g xs
smap-with h (z ∷ _)  (here y)  = here (h z y)
smap-with h (_ ∷ zs) (next ys) = next (smap-with h zs ys)

-- Eliminate a heterogenous sum whose indexing function is constant into a single value.
-- This is the dual of `forget` for `HList`.
squash : ∀ {ℓ ℓ'} → {α : Set ℓ} {β : Set ℓ'} {xs : List α} → HSum (λ _ → β) xs → β
squash (here y)  = y
squash (next ys) = squash ys

-- Retrieve the element of the list at the given index.
inject : ∀ {ℓ ℓ'} → {α : Set ℓ} {f : α → Set ℓ'} {xs : List α} → ∀ i → f (lookup xs i) → HSum f xs
inject {xs = _ ∷ _} zero    x = here x
inject {xs = _ ∷ _} (suc i) x = next (inject i x)

-- The derived form eliminating a heterogenous sum into a value.
-- This is the dual of `forget-map` for `HList`.
case-of : ∀ {ℓ ℓ' ℓ''} → {α : Set ℓ} {β : Set ℓ'} {f : α → Set ℓ''} →
          ∀ {xs} → HSum f xs → (∀ {x} → f x → β) → β
case-of ys h = squash (smap h ys)

-- The derived form eliminating a heterogenous sum into a value,
-- with access to corresponding elements of a heterogenous list.
case-of-with : ∀ {ℓ ℓ' ℓ'' ℓ'''} → {α : Set ℓ} {β : Set ℓ'} {f : α → Set ℓ''} {r : α → Set ℓ'''} →
               ∀ {xs} → HList r xs → HSum f xs → (∀ {x} → r x → f x → β) → β
case-of-with zs ys h = squash (smap-with h zs ys)
